name : "Multi Event Pipeline / Workflow"
on:
  push:
    branches:
      - production
      - master
      - main
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Running on master/test push"
        run: echo "Running on master/test push"
  on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: "Running on master/test pull request"
        run: echo "Running on master/test pull request"
  on-workflow-dispatch:
    runs-on: ubuntu-latest
      steps:
        - name: "Running on workflow dispatch"
          run: echo "Running on workflow dispatch"
